// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMsRg6hP8YhZ7X5AeXirxAwYdMuQkiHco',
    appId: '1:230211327218:web:d0695e1dc43f35dcb56c6b',
    messagingSenderId: '230211327218',
    projectId: 'myproj-ed279',
    authDomain: 'myproj-ed279.firebaseapp.com',
    storageBucket: 'myproj-ed279.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsRg6hP8YhZ7X5AeXirxAwYdMuQkiHco',
    appId: '1:230211327218:android:d0695e1dc43f35dcb56c6b',
    messagingSenderId: '230211327218',
    projectId: 'myproj-ed279',
    databaseURL: 'https://myproj-ed279.firebaseio.com',
    storageBucket: 'myproj-ed279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMsRg6hP8YhZ7X5AeXirxAwYdMuQkiHco',
    appId: '1:230211327218:ios:d0695e1dc43f35dcb56c6b',
    messagingSenderId: '230211327218',
    projectId: 'myproj-ed279',
    storageBucket: 'myproj-ed279.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'YOUR_DATABASE_URL',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'YOUR_MACOS_BUNDLE_ID',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMsRg6hP8YhZ7X5AeXirxAwYdMuQkiHco',
    appId: '1:230211327218:web:d0695e1dc43f35dcb56c6b',
    messagingSenderId: '230211327218',
    projectId: 'myproj-ed279',
    storageBucket: 'myproj-ed279.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'YOUR_DATABASE_URL',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );
}
